name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    name: Test puppeteer
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3.5.3

      - name: Test action
        uses: tj-actions/puppeteer@v4
        id: puppeteer-test
        with:
          files: test/test.js

      - name: Copy test output
        uses: tj-actions/docker-cp@v2
        with:
          container: ${{ steps.puppeteer-test.outputs.container-id }}
          source: ${{ steps.puppeteer-test.outputs.home }}/test.pdf
          destination: test.pdf

#      - name: Display contents of test.pdf
#        run: cat test.pdf

      - name: Commit and push
        uses: EndBug/add-and-commit@v7
        with:
          add: '["test.pdf"]'
          message: 'My commit message'
          push: true

        # Upload the file to Artifact
      - uses: actions/upload-artifact@v3
        with:
          name: test.pdf
          path: test.pdf
