name: Generate documentation PDF (REUSABLE)

# on:
#  workflow_call:
#    inputs:
#      VERSION:
#        required: true
#        type: string
on:
  push:
    branches:
    - main
    paths:
    # Only rebuild website when docs have changed
    # Comment out when testing locally via act!
    #- 'docs01/**'
    - 'mkdocs.yml'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Prepare
      - name: Checkout source code
        uses: actions/checkout@v3
      - name: Install Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install doc requirements
        run: pip install -r docs/requirements.txt
      - name: Install chromium
        run: sudo apt install chromium-browser
      - name: Install node
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install puppeteer
        run: npm i --save puppeteer
      - name: Run mkdocs serve in background
        run: mkdocs serve & sleep 10
      - name: Run pdf script
        run: node docs/misc/pdf.js http://localhost:8000/print_page/ iowa_documentation_v0.0.pdf 'iowa documentation v0.0'
        #run: node docs/misc/pdf.js http://localhost:8000/print_page/ iowa_documentation_v${{ inputs.VERSION }}.pdf 'iowa documentation v${{ inputs.VERSION }}'
        
      - name: Commit and push
        uses: EndBug/add-and-commit@v7
        with:
          add: '["iowa_documentation_v0.0.pdf"]'
          message: 'My commit message'
          push: true

        # Upload the file to Artifact
      - uses: actions/upload-artifact@v3
        with:
          name: iowa_documentation_v0.0.pdf
          path: iowa_documentation_v0.0.pdf
